### ISSUE TITLE
Ability for auto url conf to serve an app at /

### ISSUE THREAD

**Issue by benbacardi** [mikebryant/django-autoconfig#28]

**Comment by mikebryant** [comment]
Technically, this is possible by using `AUTOCONFIG_EXTRA_URLS`

Though then you'll have the app in the urlconf twice, so it may not reverse things the way you want

**Comment by mikebryant** [comment]
Maybe we should add a setting like:
```python
AUTOCONFIG_URL_PREFIXES = {
    'app_name': '',
    'other_app': 'some_url',
}
```

**Comment by benbacardi** [comment]
Do we need a dict? If this is in `autoconfig.py` it'll be inside a single app, so do we need to specify _other_ app's prefixes?

```python
AUTOCONFIG_URL_PREFIX = '',
```

**Comment by mikebryant** [comment]
I don't really like the idea of the autourlconf looking inside every module's autoconfig.
I like the idea of a dict because then an app might specify it itself, or you could specify changes at deployment time

**Comment by benbacardi** [comment]
Oh I see, sorry - it's a Django setting, not an option inside `autoconfig.py`. Yes, that makes more sense.
